[pytest]
addopts = --self-contained-html --capture=tee-sys


markers =
    login: DealWallet login page tests
    home: DealWallet home page tests
    categories: Categories page tests
    deals: Deals page tests
    stores: Stores page tests
    coupons: Coupons page tests